name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: ech https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

